name: DVC Tracking with Github Actions
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running_updates
        run: |
          pip install -r requirements.txt
          dvc repro
          git fetch --prune
          dvc metrics diff main
